tree={'Cairo': ['Shubrā al Khaymah', 'Ḩalwān', 'Giza', 'Mīt Namā'],
 'Giza': ['Shubrā al Khaymah', 'Ḩalwān', 'Cairo', 'Birqāsh'],
 'Alexandria': ['Abū Qīr', 'Kafr ad Dawwār', 'Burj al ‘Arab', 'Cairo'],
 'Madīnat as Sādis min Uktūbar': ['Birqāsh',
  'Ḩalwān',
  'Giza',
  'Shibīn al Kawm'],
 'Shubrā al Khaymah': ['Cairo', 'Ḩalwān', 'Biyahmū', 'Mīt Namā'],
 'Al Manşūrah': ['Kafr Sa‘d', 'Hihyā', 'Samannūd', 'Kafr ash Shaykh'],
 'Ḩalwān': ['Bilbays', 'Giza', 'Qiman al ‘Arūs', 'Mīt Namā'],
 'Al Maḩallah al Kubrá': ['Kafr Sa‘d', 'Samannūd', 'Ţanţā', 'Kafr ash Shaykh'],
 'Port Said': ['Al Manşūrah', 'Būr Fu’ād', 'Ismailia', 'Damietta'],
 'Suez': ['Ḩalwān', 'Cairo', 'Qiman al ‘Arūs', 'Fāyīd'],
 'Ţanţā': ['Sunbāţ', 'Ziftá', 'Al Maḩallah al Kubrá', 'Sakhā'],
 'Asyūţ': ['Banī Murr', 'Sūhāj', 'Al Khārjah', 'Abnūb'],
 'Al Fayyūm': ['Biyahmū', 'Ihnāsyā al Madīnah', 'Abjīj', 'Damanhūr'],
 'Az Zaqāzīq': ['Hirrīyat Raznah', 'Bilbays', 'Banhā', 'Mīt Ghamr'],
 'Ismailia': ['Az Zaqāzīq', 'Fāyīd', 'Port Said', 'Al Ḩusaynīyah'],
 'Kafr ad Dawwār': ['Rosetta', 'Alexandria', 'Burj al ‘Arab', 'Abū Qīr'],
 'Aswān': ['Darāw', 'Barnīs', 'Idfū'],
 'Damanhūr': ['Disūq', 'Kafr ad Dawwār', 'Burj al ‘Arab', 'Rosetta'],
 'Al Minyā': ['Ţihnā al Jabal', 'Sawādah', 'Al Fayyūm', 'Samālūţ'],
 'Damietta': ['Al Manşūrah', 'Būr Fu’ād', 'Fāraskūr', 'Port Said'],
 'Qinā': ['Safājā', 'Qifţ', 'Dandarah', 'Jirjā'],
 'Banī Suwayf': ['Qiman al ‘Arūs',
  'Al Fayyūm',
  'Dishāshah',
  'Ihnāsyā al Madīnah'],
 'Luxor': ['Al Karnak', 'Idfū', 'Armant', 'Naj‘ Ḩammādī'],
 'Sūhāj': ['Akhmīm', 'Jirjā', 'Al Khārjah', 'Banī Murr'],
 'Shibīn al Kawm': ['Sunbāţ', 'Munūf', 'Ţanţā', 'Az Zaqāzīq'],
 'Al ‘Arīsh': ['Ismailia', 'Port Said', 'Al Ḩusaynīyah', 'Būr Fu’ād'],
 'Banhā': ['Kafr Shukr', 'Qahā', 'Az Zaqāzīq', 'Munūf'],
 'Al Ghardaqah': ['Qinā', 'Safājā', 'Dandarah', 'Ra’s Ghārib'],
 'Kafr ash Shaykh': ['Damanhūr', 'Samannūd', 'Sakhā', 'Disūq'],
 'Mallawī': ['Dayr al Barshā', 'Dayr Mawās', 'Al Qūşīyah', 'Sawādah'],
 'Disūq': ['Damanhūr', 'Sakhā', 'Burj al ‘Arab', 'Kafr ash Shaykh'],
 'Bilbays': ['Hihyā', 'Az Zaqāzīq', 'Mīt Namā', 'Hirrīyat Raznah'],
 'Idfū': ['Safājā', 'Kawm Umbū', 'Al Ghardaqah', 'Isnā'],
 'Mīt Ghamr': ['Banhā', 'Kafr Shukr', 'Ziftá', 'Mīt Damsīs'],
 'Munūf': ['Kafr Shukr', 'Shibīn al Kawm', 'Ţanţā', 'Banhā'],
 'Jirjā': ['Safājā', 'Al Balyanā', 'Al Khārjah', 'Akhmīm'],
 'Akhmīm': ['Sūhāj', 'Al Balyanā', 'Al Khārjah', 'Jirjā'],
 'Ziftá': ['Samannūd', 'Ţanţā', 'Mīt Ghamr', 'Sunbāţ'],
 'Manfalūţ': ['Qiman al ‘Arūs', 'Banī Murr', 'Banī Suwayf', 'Al Qūşīyah'],
 'Maghāghah': ['Al Ḩībah', 'Shārūnah', 'Qufādah', 'Abjīj'],
 'Al Qūşīyah': ['Dayr Mawās', 'Banī Murr', 'Mallawī', 'Manfalūţ'],
 'Abnūb': ['Qiman al ‘Arūs', 'Banī Murr', 'Al Khārjah', 'Asyūţ'],
 'Samannūd': ['Ziftá', 'Al Maḩallah al Kubrá', 'Al Manşūrah', 'Mīt Ghamr'],
 'Abū Qīr': ['Alexandria', 'Sakhā', 'Burj al ‘Arab', 'Kafr ad Dawwār'],
 'Al Khārjah': ['Banī Murr', 'Isnā', 'Asyūţ', 'Al Qaşr'],
 'Al Balyanā': ['Safājā', 'Jirjā', 'Al Ghardaqah', 'Qinā'],
 'Naj‘ Ḩammādī': ['Dandarah', 'Al Balyanā', 'Qinā', 'Luxor'],
 'Al Karnak': ['Luxor', 'Naj‘ Ḩammādī', 'Armant', 'Idfū'],
 'Qiman al ‘Arūs': ['Banī Suwayf',
  'Madīnat as Sādis min Uktūbar',
  'Ihnāsyā al Madīnah',
  'Biyahmū'],
 'Qahā': ['Kafr Shukr', 'Mīt Namā', 'Birqāsh', 'Shubrā al Khaymah'],
 'Hirrīyat Raznah': ['Az Zaqāzīq', 'Mīt Ghamr', 'Kafr Shukr', 'Bilbays'],
 'Mīt Namā': ['Giza', 'Qahā', 'Bilbays', 'Shubrā al Khaymah'],
 'Kafr Shukr': ['Banhā', 'Mīt Ghamr', 'Az Zaqāzīq', 'Mīt Damsīs'],
 'Shārūnah': ['Al Ḩībah', 'Maghāghah', 'Banī Mazār', 'Dayr al Jarnūs'],
 'Banī Murr': ['Asyūţ', 'Abnūb', 'Ḩalwān', 'Dayr al Barshā'],
 'Sunbāţ': ['Mīt Damsīs', 'Al Maḩallah al Kubrá', 'Samannūd', 'Ziftá'],
 'Banī Ḩasan ash Shurūq': ['Mallawī', 'Al Minyā', 'Dayr Mawās', 'Sawādah'],
 'Biyahmū': ['Al Fayyūm', 'Ihnāsyā al Madīnah', 'Abjīj', 'Qiman al ‘Arūs'],
 'Al Madāmūd': ['Al Karnak', 'Naj‘ Ḩammādī', 'Armant', 'Dandarah'],
 'Birqāsh': ['Madīnat as Sādis min Uktūbar', 'Munūf', 'Qahā', 'Mīt Namā'],
 'Mīt Damsīs': ['Sunbāţ', 'Al Maḩallah al Kubrá', 'Samannūd', 'Mīt Ghamr'],
 'Aţ Ţūr': ['Qinā', 'Safājā', 'Dandarah', 'Al Ghardaqah'],
 'Qufādah': ['Dishāshah', 'Banī Mazār', 'Maghāghah', 'Dayr al Jarnūs'],
 'Shanhūr': ['Qifţ', 'Qinā', 'Armant', 'Naqādah'],
 'Dayr al Jarnūs': ['Al Ḩībah', 'Banī Mazār', 'Dayr as Sanqūrīyah', 'Qufādah'],
 'Samālūţ': ['Maţāy', 'Ţihnā al Jabal', 'Qufādah', 'Al Minyā'],
 'Banī Mazār': ['Samālūţ', 'Qufādah', 'Maţāy', 'Banī Ḩasan ash Shurūq'],
 'Armant': ['Naqādah', 'Isnā', 'Luxor', 'Idfū'],
 'Kawm Umbū': ['Aswān', 'Idfū', 'Darāw', 'Isnā'],
 'Būr Fu’ād': ['Ismailia', 'Port Said', 'Al Ḩusaynīyah', 'Fāraskūr'],
 'Rosetta': ['Kafr ad Dawwār', 'Sakhā', 'Burj al ‘Arab', 'Disūq'],
 'Isnā': ['Naqādah', 'Armant', 'Luxor', 'Idfū'],
 'Hihyā': ['Hirrīyat Raznah', 'Mīt Ghamr', 'Port Said', 'Ismailia'],
 'Maţrūḩ': ['Kafr Sa‘d', 'Aḑ Ḑab‘ah', 'Sīwah', 'As Sallūm'],
 'Dandarah': ['Naj‘ Ḩammādī', 'Qifţ', 'Qinā', 'Shanhūr'],
 'Maţāy': ['Samālūţ', 'Qufādah', 'Banī Mazār', 'Dayr as Sanqūrīyah'],
 'Şān al Ḩajar al Qiblīyah': ['Hihyā', 'Al Ḩusaynīyah', 'Qantīr', 'Fāraskūr'],
 'Dayr Mawās': ['Dayr al Barshā',
  'Mallawī',
  'Banī Ḩasan ash Shurūq',
  'Manfalūţ'],
 'Ihnāsyā al Madīnah': ['Maghāghah', 'Al Fayyūm', 'Dishāshah', 'Banī Suwayf'],
 'Fāraskūr': ['Al Manşūrah', 'Al Ḩusaynīyah', 'Damietta', 'Kafr Sa‘d'],
 'Darāw': ['Aswān', 'Idfū', 'Kawm Umbū', 'Naqādah'],
 'Ra’s Ghārib': ['Samālūţ', 'Safājā', 'Ţihnā al Jabal', 'Al Ghardaqah'],
 'Al Ḩusaynīyah': ['Hihyā', 'Şān al Ḩajar al Qiblīyah', 'Qantīr', 'Ismailia'],
 'Safājā': ['Qinā', 'Al Ghardaqah', 'Qifţ', 'Dayr al Barshā'],
 'Al Quşayr': ['Shanhūr', 'Safājā', 'Qifţ', 'Dayr al Barshā'],
 'Qifţ': ['Shanhūr', 'Qinā', 'Naqādah', 'Idfū'],
 'Kafr Sa‘d': ['Al Manşūrah', 'Qantīr', 'Damietta', 'Fāraskūr'],
 'Sīwah': ['Aḑ Ḑab‘ah', 'Mandīshah', 'Maţrūḩ', 'As Sallūm'],
 'Fāyīd': ['Mīt Namā', 'Ismailia', 'Būr Fu’ād', 'Suez'],
 'Naqādah': ['Armant', 'Dandarah', 'Qifţ', 'Shanhūr'],
 'Dayr Abū Ḩinnis': ['Mallawī', 'Dayr al Barshā', 'Banī Suwayf', 'Manfalūţ'],
 'Al Ḩībah': ['Maghāghah', 'Al Fayyūm', 'Banī Suwayf', 'Dishāshah'],
 'Sakhā': ['Damanhūr', 'Disūq', 'Kafr ash Shaykh', 'Al Maḩallah al Kubrá'],
 'Qantīr': ['Hihyā', 'Al Manşūrah', 'Al Ḩusaynīyah', 'Ismailia'],
 'Sidmant al Jabal': ['Al Ḩībah', 'Al Fayyūm', 'Dishāshah', 'Banī Suwayf'],
 'Dayr al Barshā': ['Mallawī', 'Dayr Abū Ḩinnis', 'Al Ḩībah', 'Manfalūţ'],
 'Aḑ Ḑab‘ah': ['Sīwah', 'Al ‘Alamayn', 'Alexandria', 'Shibīn al Kawm'],
 'Dishāshah': ['Maghāghah', 'Al Fayyūm', 'Ihnāsyā al Madīnah', 'Al Ḩībah'],
 'Burj al ‘Arab': ['Sīwah', 'Aḑ Ḑab‘ah', 'Alexandria', 'Ţanţā'],
 'Sawādah': ['Abjīj', 'Al Minyā', 'Banī Mazār', 'Ţihnā al Jabal'],
 'Abjīj': ['Dayr al Jarnūs', 'Damanhūr', 'Al Fayyūm', 'Ihnāsyā al Madīnah'],
 'Dayr as Sanqūrīyah': ['Al Khārjah',
  'Ţihnā al Jabal',
  'Dayr al Jarnūs',
  'Maţāy'],
 'Ţihnā al Jabal': ['Al Minyā', 'Samālūţ', 'Banī Mazār', 'Sawādah'],
 'As Sallūm': ['Al ‘Alamayn', 'Maţrūḩ'],
 'Al ‘Alamayn': ['Sīwah', 'Aḑ Ḑab‘ah', 'Burj al ‘Arab', 'Shibīn al Kawm'],
 'Mandīshah': ['Sīwah', 'Madīnat as Sādis min Uktūbar', 'Samālūţ'],
 'Qaşr al Farāfirah': ['Al Qaşr', 'Mandīshah', 'Al Khārjah'],
 'Al Qaşr': ['Qaşr al Farāfirah', 'Mandīshah', 'Al Khārjah'],
 'Barnīs': ['Al Quşayr']}
